# version: "3.8"

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"

#   frontend:
#     build: ./frontend
#     ports:
#       - "8501:8501"
#     depends_on:
#       - backend

# Use official Python image as base
# Use official Python image as base
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app files
COPY . .

# Expose FastAPI and Streamlit ports
EXPOSE 8000
EXPOSE 8501

# Start FastAPI and Streamlit separately
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
