services:
  - name: titanic-backend
    type: web
    env: python
    runtime: docker
    repo: https://github.com/DivSingh77/AI_Chat_Assistant
    branch: main
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - name: titanic-frontend
    type: web
    env: python
    runtime: docker
    repo: https://github.com/DivSingh77/AI_Chat_Assistant
    branch: main
    rootDir: frontend
    plan: free
    envVars:
      - key: PORT
        value: 8501
