# services:
#   - name: titanic-backend
#     type: web
#     runtime: python
#     rootDirectory: backend
#     buildCommand: pip install -r requirements.txt
#     startCommand: uvicorn main:app --host 0.0.0.0 --port 8000

#   - name: titanic-frontend
#     type: web
#     runtime: python
#     rootDirectory: frontend
#     buildCommand: pip install -r requirements.txt
#     startCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0

  # - name: titanic-main
  #   type: web
  #   runtime: python
  #   rootDirectory: .
  #   buildCommand: pip install -r requirements.txt
  #   startCommand: python run.py


services:
  - name: titanic-main
    type: web
    runtime: python
    rootDirectory: .
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
